### ISSUE TITLE
Running RolyPoly with the example data and not working

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [dcalderon/rolypoly#13]
Hello, 

Im trying to run RolyPoly with the example data available in this GitHub page and is not working. I don't know how to interpret the error Im getting. 

`Error in { : task 1 failed - "argument 'description' not valid"` 

The error comes when it tries to link the GWAS with the BLOCK annotation obj. 

This is what Im running: 

```
load("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/PAPERS/Integration_GWAS_scRNA-seq/ROLYPOLY/sim_gwas_data.rda")
load("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/PAPERS/Integration_GWAS_scRNA-seq/ROLYPOLY/sim_expression_data_normalized.rda")
load("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/PAPERS/Integration_GWAS_scRNA-seq/ROLYPOLY/sim_block_annotation.rda")
data <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/PAPERS/Integration_GWAS_scRNA-seq/ROLYPOLY/1.Rds")

rp <- rolypoly_roll(gwas_data =sim_gwas_data ,block_annotation = sim_block_annotation,block_data = sim_expression_data_normalized,ld_folder = data)
```

This is the part where the error is generate: 

```
function (obj, ex) 
{
  e <- getDoSeq()
  environment(e$fun) <- new.env(parent = environment(e$fun))
  environment(e$fun)$.foreach_do <- TRUE
  e$fun(obj, substitute(ex), parent.frame(), e$data)
}
```
Also I tried in different system (MAC and LINUX) and still getting the same error
Hope someone can help : ) 

Thanks in advanced!

**Comment by dcalderon** [comment]
Hello, apologies for the confusion, the ld_folder parameter should be a character that indicates the path of the LD data as opposed to the LD data itself. So, based on the code included it should probably be set to something like: "3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/PAPERS/Integration_GWAS_scRNA-seq/ROLYPOLY/". In case it helps, the vignettes aren't super accessible from CRAN anymore, but the code should be still be available [here](https://github.com/dcalderon/rolypoly/blob/master/vignettes/intro.Rmd) and could serve as a more clear example of how to run the test code. I hope this helps! For now I'll close this issue, but feel free to re-open if it was something else.

**Comment by dcalderon** [comment]
As I mentioned in the other issue, I'll keep this closed and try and figure out the error in the other thread.
