### ISSUE TITLE
ERROR: "Error in { : task 1 failed - "cant find the function ".""

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [dcalderon/rolypoly#14]
Hello! 

I manage to run the example! But know Im having kind of the same issue with my data. 

This is the error Im getting: 

`Error in { : task 1 failed - "cant find the function ".""`

I get the error in the same place as the other one: 

```
function (obj, ex) 
{
  e <- getDoSeq()
  environment(e$fun) <- new.env(parent = environment(e$fun))
  environment(e$fun)$.foreach_do <- TRUE
  e$fun(obj, substitute(ex), parent.frame(), e$data)
}
```

This is the data Im using: 

```
gwas_data <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/4_Try_RolyPoly/gwas.filtrado.rds")
Gene_annotation <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/4_Try_RolyPoly/block.of.annotations.rds")
annonorm <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/4_Try_RolyPoly/matriz.filtrada.tejidos.ENSG.rds")
ld_path <- "3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/2_LD.Matrix/"
```

As suggested the ld_path now is a path and is going to a folder where I have a .rds object with the ld information for each chromosome. 

Any idea where Im wrong? 

Thanks in advanced, 

ANE

**Comment by anemartinezlarrinaga2898** [comment]
Did a comment about this error in this issue: https://github.com/dcalderon/rolypoly/issues/13

**Comment by dcalderon** [comment]
Great! It's probably best to keep the other issue closed and we can try and figure out this new error here. 

Hmm, I'm not quite sure of the issue now with just this information. Could you include the rolypoly function call?

**Comment by anemartinezlarrinaga2898** [comment]
Hi!

Thank you for the quickly reply. 

I stabilized the ld_path correctly according to yours previous answer, also checking the other objects Im seeing that is clarifying the genes correctly attending to the chromosome where they are located (chrom_gwas_list)

I think the issue comes when trying to open de LD_Matrix for each chromosome. If I worked with the LD_Matrix from the examples it works but If I try to used mines they don't. Im also working with an .RDS obj. 

```
rp <- rolypoly_roll(gwas_data = gwas_data,
                    block_annotation = Gene_annotation,
                    block_data = annonorm,
                    ld_folder = ld_path)
```

**Comment by anemartinezlarrinaga2898** [comment]
Hello, 

This the whole code : 

```
directory <- setwd("/Users/amartinezl/OneDrive - Josep Carreras Leukaemia Research Institute (IJC)/2_PhD/2_CELLULAR_SYSTEMS_GENOMICS/")

library(rolypoly)

gwas_data <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/4_Try_RolyPoly/gwas.filtrado.rds")
Gene_annotation <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/4_Try_RolyPoly/block.of.annotations.rds")
annonorm <- readRDS("3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/4_Try_RolyPoly/matriz.filtrada.tejidos.ENSG.rds")
ld_path <- "./3_MEREU_PBMC_IMMUNE_ATLAS/1_ANALISIS/3_Gwas/2_LD.Matrix"
rp <- rolypoly_roll(gwas_data = gwas_data,
                    block_annotation = Gene_annotation,
                    block_data = annonorm,
                    ld_folder = ld_path)

```

And the full error is what I posted at the beggining: 

```
adding gwas
filtering out SNPs with MAF < 1%
adding block annotations
beginning processs of linking gwas and block annotations
Error in { : task 1 failed - "can't find the function ".""
```

And the ld_path folder has the following structure: 
<img width="725" alt="Captura de pantalla 2022-06-23 a las 8 37 07" src="https://user-images.githubusercontent.com/80770004/175231639-e206c18c-9934-49d4-bb0d-cf26e238c4f8.png">

I wasn't able to download the versions you generated, they are posted in a Drive where you need to ask for permission, I did it but never get an answer back. 

Thanks : )

**Comment by anemartinezlarrinaga2898** [comment]
This last link actually works. 

Will try with your LD files and will keep you update about it!

However, what data did you use to generate the LD files? Did you use PLINK with the 1000 Genomes from European population? Or did you use other different approach? Is to know where the error might be. 

Thanks!

**Comment by dcalderon** [comment]
Great! Sounds good, let me know. Yes, I used PLINK with the VCFs from 1000 Genomes phase 3 from the EUR population.

**Comment by anemartinezlarrinaga2898** [comment]
I tried with you LD data and it did worked, so my LD files must be wrong but don't know where I made the mistake as I also used PLINK with the files from 1000 Genomes. 

Thank you for your help and for sharing the LD data!

**Comment by dcalderon** [comment]
Excellent, glad it worked out!
