### ISSUE TITLE
Error while using a different LD file

### ISSUE THREAD

**Issue by saimukund20** [dcalderon/rolypoly#4]
Hi Diego,

I tried to run the rolypoly pipeline using the codes from this link: https://cran.r-project.org/web/packages/rolypoly/vignettes/intro.html

When I use the LD file (1.Rds) in the code it runs perfectly with the example sim files. But when I run the same with the LD files (1.Rds) provided in the link underneath the Linkage disequilibrium section (https://drive.google.com/file/d/0B_X6s0BThq9ZXzNNbjk3V2hNdlk/view?usp=sharing) I get an error saying:

adding gwas
filtering out SNPs with MAF < 1%
adding block annotations
beginning processs of linking gwas and block annotations
Error in { : task 1 failed - "invalid 'description' argument”

Could you help me out in debugging this?

**Comment by dcalderon** [comment]
The `ld_folder` parameter within the `rolypoly_roll` function should be a string containing the path to the folder with all the LD data.

**Comment by akshatkarambe** [comment]
I have the correct string containing the path  but still its not working. Why is that so?
Can we have all the data concatenated into one file and can we pass that file in the function?
