### ISSUE TITLE
Error in rolypoly_load_block_data

### ISSUE THREAD

**Issue by dg13** [dcalderon/rolypoly#7]
Hi,
We're getting an error in creating the rolypoly data object with the following message:

adding gwas
filtering out SNPs with MAF < 1%
adding block annotations
beginning processs of linking gwas and block annotations
merging functional information about blocks
Error in block$ld_matrix_squared %*% x : 
  requires numeric/complex matrix/vector arguments
Calls: rolypoly_roll ... rolypoly_load_block_data -> lapply -> FUN -> as.matrix
Execution halted

I'm not really sure how to debug this. Can anyone help?
Dan

**Comment by dg13** [comment]
Yes it was we were running with "gwas_link_parallel=TRUE,bootstrap_parallel=TRUE". I'll give it a shot with these turned off (although it took 25 hours to run with these on, so not sure how long it will take without)

**Comment by dcalderon** [comment]
Ok, let me know. Might be worth running with a few genes and low number of bootstraps to check if the error remains.

As for runtime there are various aspects that can be manually parallelized. There are two aspects that take a bit of time. Organizing the data and then performing the bootstrap estimates of the model fit. One possibility would be to run the data organizing for a trait then store that to disk. Then, for each gene expression data set you could run a separate rolypoly instance using the previously stored organized trait data.

Functions for doing this can be found in the [main_wrapper](https://github.com/dcalderon/rolypoly/blob/master/R/main_wrapper.R) code. A majority of the function calls there are for organizing data and you would save the rolypoly object after `rolypoly_link_blocks_and_gwas`. Then for an expression data set run `rolypoly_load_block_data` and `rolypoly_perform_inference` on the saved object.

**Comment by dg13** [comment]
Thanks Diego - we did try with a very small data set and the parallel options set before running the entire thing and it seemed to exit OK, so not sure why its happened with the larger data set. I'll try and run without parallel options and see how that goes.
